---@diagnostic disable: undefined-global
-- Auto-generated from InfinityBoss private aura pipeline. Do not edit manually.
_G.InfinityBoss_PRIVATE_AURA_DATA = {
    raid = {
        [3176] = {
            encounterID = 3176,
            dungeon = "Phantom Spire",
            boss = "Primarch Afozhan (Imperator Averzian)",
            spells = {
                [1249265] = {
                    spellID = 1249265,
                    name = "Shadow Collapse",
                    sourceNPCIDs = {240435},
                    sources = {"Imperator Averzian"},
                },
                [1255680] = {
                    spellID = 1255680,
                    name = "Gnaw the Void",
                    sourceNPCIDs = {251176},
                    sources = {"Voidmaw"},
                },
                [1260203] = {
                    spellID = 1260203,
                    name = "Shadow Collapse",
                    sourceNPCIDs = {240435},
                    sources = {"Imperator Averzian"},
                },
                [1265540] = {
                    spellID = 1265540,
                    name = "Dark Wound",
                    sourceNPCIDs = {240435},
                    sources = {"Imperator Averzian"},
                },
                [1284786] = {
                    spellID = 1284786,
                    name = "Shadow Array",
                    sourceNPCIDs = {260629},
                    sources = {"Obscurion Endwalker"},
                },
            },
        },
        [3177] = {
            encounterID = 3177,
            dungeon = "Phantom Spire",
            boss = "Frashius (Vorasius)",
            spells = {
                [1241844] = {
                    spellID = 1241844,
                    name = "Crush",
                    sourceNPCIDs = {240434},
                    sources = {"Vorasius"},
                },
                [1254113] = {
                    spellID = 1254113,
                    name = "Lock On",
                    sourceNPCIDs = {253475, 255418},
                    sources = {"Blistercreep"},
                },
                [1259186] = {
                    spellID = 1259186,
                    name = "Bubble Burst",
                    sourceNPCIDs = {253475},
                    sources = {"Blistercreep"},
                },
                [1272527] = {
                    spellID = 1272527,
                    name = "Crawling Spit",
                    sourceNPCIDs = {253475, 255418},
                    sources = {"Blistercreep"},
                },
            },
        },
        [3178] = {
            encounterID = 3178,
            dungeon = "Phantom Spire",
            boss = "Ve'gor and Aizolak (Vaelgor & Ezzorak)",
            spells = {
                [1244672] = {
                    spellID = 1244672,
                    name = "Void Realm",
                    sourceNPCIDs = {242056},
                    sources = {"Vaelgor"},
                },
                [1245175] = {
                    spellID = 1245175,
                    name = "Void Arrow",
                    sourceNPCIDs = {248143},
                    sources = {"Voidorb"},
                },
                [1245421] = {
                    spellID = 1245421,
                    name = "Murk Zone",
                    sourceNPCIDs = {244552},
                    sources = {"Ezzorak"},
                },
                [1245554] = {
                    spellID = 1245554,
                    name = "Murk Touch",
                    sourceNPCIDs = {244552},
                    sources = {"Ezzorak"},
                },
                [1249595] = {
                    spellID = 1249595,
                    name = "Radiant Barrier",
                    sourceNPCIDs = {},
                    sources = {"War Chaplain Senn"},
                },
                [1255612] = {
                    spellID = 1255612,
                    name = "Undead Breath",
                    sourceNPCIDs = {242056},
                    sources = {"Vaelgor"},
                },
                [1255763] = {
                    spellID = 1255763,
                    name = "Midnight Avatar",
                    sourceNPCIDs = {253342},
                    sources = {"Xal'atath"},
                },
                [1262676] = {
                    spellID = 1262676,
                    name = "Void Beam",
                    sourceNPCIDs = {242056},
                    sources = {"Vaelgor"},
                },
                [1264467] = {
                    spellID = 1264467,
                    name = "Dragon Tail Sweep",
                    sourceNPCIDs = {242056},
                    sources = {"Vaelgor"},
                },
                [1265152] = {
                    spellID = 1265152,
                    name = "Pierce",
                    sourceNPCIDs = {244552},
                    sources = {"Ezzorak"},
                },
                [1280355] = {
                    spellID = 1280355,
                    name = "Rak's Fang",
                    sourceNPCIDs = {244552},
                    sources = {"Ezzorak"},
                },
            },
        },
        [3179] = {
            encounterID = 3179,
            dungeon = "Phantom Spire",
            boss = "The Fallen King Sahadar (Fallen-King Salhadaar)",
            spells = {
                [1245592] = {
                    spellID = 1245592,
                    name = "Agony Essence",
                    sourceNPCIDs = {240432},
                    sources = {"Fallen-King Salhadaar"},
                },
                [1248697] = {
                    spellID = 1248697,
                    name = "Tyrannical Command",
                    sourceNPCIDs = {240432},
                    sources = {"Fallen-King Salhadaar"},
                },
                [1248709] = {
                    spellID = 1248709,
                    name = "Oppressive Darkness",
                    sourceNPCIDs = {240432},
                    sources = {"Fallen-King Salhadaar"},
                },
                [1250686] = {
                    spellID = 1250686,
                    name = "Twisted Veil",
                    sourceNPCIDs = {240432},
                    sources = {"Fallen-King Salhadaar"},
                },
                [1250828] = {
                    spellID = 1250828,
                    name = "Void Exposed",
                    sourceNPCIDs = {246665},
                    sources = {"Concentrated Void"},
                },
                [1250991] = {
                    spellID = 1250991,
                    name = "Dark Erosion",
                    sourceNPCIDs = {246665},
                    sources = {"Concentrated Void"},
                },
                [1251213] = {
                    spellID = 1251213,
                    name = "Twilight Spike",
                    sourceNPCIDs = {240432},
                    sources = {"Fallen-King Salhadaar"},
                },
                [1260030] = {
                    spellID = 1260030,
                    name = "Umbra Burst",
                    sourceNPCIDs = {240432},
                    sources = {"Fallen-King Salhadaar"},
                },
                [1271579] = {
                    spellID = 1271579,
                    name = "Shadow-Erode Strike",
                    sourceNPCIDs = {240432},
                    sources = {"Fallen-King Salhadaar"},
                },
            },
        },
        [3180] = {
            encounterID = 3180,
            dungeon = "Phantom Spire",
            boss = "Light-Blind Vanguard (Lightblinded Vanguard)",
            spells = {
                [1246487] = {
                    spellID = 1246487,
                    name = "Avenger's Shield",
                    sourceNPCIDs = {240431},
                    sources = {"General Amias Bellamy"},
                },
                [1246502] = {
                    spellID = 1246502,
                    name = "Avenger's Shield",
                    sourceNPCIDs = {240431},
                    sources = {"General Amias Bellamy"},
                },
                [1246736] = {
                    spellID = 1246736,
                    name = "Judgment",
                    sourceNPCIDs = {240437},
                    sources = {"Commander Venel Lightblood"},
                },
                [1248652] = {
                    spellID = 1248652,
                    name = "Holy Bell",
                    sourceNPCIDs = {240431},
                    sources = {"General Amias Bellamy"},
                },
                [1248721] = {
                    spellID = 1248721,
                    name = "Tyr's Wrath",
                    sourceNPCIDs = {240438},
                    sources = {"War Chaplain Senn"},
                },
                [1248994] = {
                    spellID = 1248994,
                    name = "Final Verdict",
                    sourceNPCIDs = {240437},
                    sources = {"Commander Venel Lightblood"},
                },
                [1249024] = {
                    spellID = 1249024,
                    name = "Final Verdict",
                    sourceNPCIDs = {240437},
                    sources = {"Commander Venel Lightblood"},
                },
                [1251857] = {
                    spellID = 1251857,
                    name = "Judgment",
                    sourceNPCIDs = {240431},
                    sources = {"General Amias Bellamy"},
                },
            },
        },
        [3181] = {
            encounterID = 3181,
            dungeon = "Phantom Spire",
            boss = "Cosmic Crown (Crown of the Cosmos)",
            spells = {
                [1227557] = {
                    spellID = 1227557,
                    name = "Devouring Cosmos",
                    sourceNPCIDs = {},
                    sources = {"Environment"},
                },
                [1232470] = {
                    spellID = 1232470,
                    name = "Grip of the Void",
                    sourceNPCIDs = {240430},
                    sources = {"Alleria Windrunner"},
                },
                [1233602] = {
                    spellID = 1233602,
                    name = "Silver Arrow",
                    sourceNPCIDs = {240430},
                    sources = {"Alleria Windrunner"},
                },
                [1233865] = {
                    spellID = 1233865,
                    name = "Crown of Nothing",
                    sourceNPCIDs = {240430, 245113},
                    sources = {"Alleria Windrunner", "Rift Simulacrum"},
                },
                [1233887] = {
                    spellID = 1233887,
                    name = "Crown of Nothing",
                    sourceNPCIDs = {},
                    sources = {"Environment"},
                },
                [1234570] = {
                    spellID = 1234570,
                    name = "Star Scatter",
                    sourceNPCIDs = {240430},
                    sources = {"Alleria Windrunner"},
                },
                [1237038] = {
                    spellID = 1237038,
                    name = "Void Hunter Spike",
                    sourceNPCIDs = {240430},
                    sources = {"Alleria Windrunner"},
                },
                [1238206] = {
                    spellID = 1238206,
                    name = "Unstable Rift",
                    sourceNPCIDs = {},
                    sources = {"Environment"},
                },
                [1238708] = {
                    spellID = 1238708,
                    name = "Dark Charge",
                    sourceNPCIDs = {},
                    sources = {"Environment"},
                },
                [1239111] = {
                    spellID = 1239111,
                    name = "Final Ward",
                    sourceNPCIDs = {240430},
                    sources = {"Alleria Windrunner"},
                },
                [1242553] = {
                    spellID = 1242553,
                    name = "Void Residue",
                    sourceNPCIDs = {240430},
                    sources = {"Alleria Windrunner"},
                },
                [1243753] = {
                    spellID = 1243753,
                    name = "Gluttonous Abyss",
                    sourceNPCIDs = {243811},
                    sources = {"Vorelus"},
                },
                [1246462] = {
                    spellID = 1246462,
                    name = "Rift Slash",
                    sourceNPCIDs = {245113},
                    sources = {"Rift Simulacrum"},
                },
                [1255453] = {
                    spellID = 1255453,
                    name = "Gravity Collapse",
                    sourceNPCIDs = {},
                    sources = {"Environment"},
                },
            },
        },
        [3306] = {
            encounterID = 3306,
            dungeon = "Dreamrift",
            boss = "Chimerus, God of the Undreamt (Chimaerus the Undreamt God)",
            spells = {
                [1245698] = {
                    spellID = 1245698,
                    name = "Aelin's Insight",
                    sourceNPCIDs = {245569},
                    sources = {"Chimaerus"},
                },
                [1246653] = {
                    spellID = 1246653,
                    name = "Corrosive Phlegm",
                    sourceNPCIDs = {245569},
                    sources = {"Chimaerus"},
                },
                [1250953] = {
                    spellID = 1250953,
                    name = "Rift Fatigue",
                    sourceNPCIDs = {248319, 248444, 249341},
                    sources = {"Colossal Horror", "Haunting Essence", "Swarming Shade"},
                },
                [1253744] = {
                    spellID = 1253744,
                    name = "Rift Vulnerable",
                    sourceNPCIDs = {245569},
                    sources = {"Chimaerus"},
                },
                [1272726] = {
                    spellID = 1272726,
                    name = "Savage Rend",
                    sourceNPCIDs = {245569},
                    sources = {"Chimaerus"},
                },
            },
        },
    },
    mplus = {
        ["Aegisar Academy"] = {
            dungeon = "Aegisar Academy",
            dungeonEN = "Algeth'ar Academy",
            spells = {
                [376760] = {
                    spellID = 376760,
                    name = "Gale Force",
                    sourceNPCIDs = {},
                    bosses = "Krolz",
                    sources = {"Goal of the Rushing Winds"},
                },
                [376997] = {
                    spellID = 376997,
                    name = "Wild Peck",
                    sourceNPCIDs = {191736},
                    bosses = "Krolz",
                    sources = {"Crawth"},
                },
                [377009] = {
                    spellID = 377009,
                    name = "Deafening Screech",
                    sourceNPCIDs = {191736},
                    bosses = "Krolz",
                    sources = {"Crawth"},
                },
                [386201] = {
                    spellID = 386201,
                    name = "Corrupt Mana",
                    sourceNPCIDs = {194181},
                    bosses = "Veksamus",
                    sources = {"Vexamus"},
                },
                [388544] = {
                    spellID = 388544,
                    name = "Treant Smash",
                    sourceNPCIDs = {196482},
                    bosses = "Ancient Treant",
                    sources = {"Overgrown Ancient"},
                },
                [389007] = {
                    spellID = 389007,
                    name = "Savage Energy",
                    sourceNPCIDs = {},
                    bosses = "Echo of Dracurgosa",
                    sources = {"Environment"},
                },
                [389011] = {
                    spellID = 389011,
                    name = "Unstoppable",
                    sourceNPCIDs = {},
                    bosses = "Echo of Dracurgosa",
                    sources = {"Environment"},
                },
                [389033] = {
                    spellID = 389033,
                    name = "Lasher Toxin",
                    sourceNPCIDs = {196642},
                    bosses = "Ancient Treant",
                    sources = {"Hungry Lasher"},
                },
                [391977] = {
                    spellID = 391977,
                    name = "Surge Overload",
                    sourceNPCIDs = {},
                    bosses = "Veksamus",
                    sources = {"Environment"},
                },
                [396716] = {
                    spellID = 396716,
                    name = "Cracked Hide",
                    sourceNPCIDs = {196482},
                    bosses = "Ancient Treant",
                    sources = {"Overgrown Ancient"},
                },
            },
        },
        ["Node Sinas"] = {
            dungeon = "Node Sinas",
            dungeonEN = "Nexus-Point Xenas",
            spells = {
                [1249020] = {
                    spellID = 1249020,
                    name = "Eclipse Step",
                    sourceNPCIDs = {241542},
                    bosses = "Core Guardian Nasara",
                    sources = {"Corewarden Nysarra"},
                },
                [1251772] = {
                    spellID = 1251772,
                    name = "Feedback Charge",
                    sourceNPCIDs = {241539},
                    bosses = "Chief Engineer Kaslesor",
                    sources = {"Kasreth"},
                },
                [1252828] = {
                    spellID = 1252828,
                    name = "Void Gash",
                    sourceNPCIDs = {241542},
                    bosses = "Core Guardian Nasara",
                    sources = {"Corewarden Nysarra"},
                },
                [1257836] = {
                    spellID = 1257836,
                    name = "Feedback Charge",
                    sourceNPCIDs = {241539},
                    bosses = "Chief Engineer Kaslesor",
                    sources = {"Kasreth"},
                },
            },
        },
        ["Saron's Mine"] = {
            dungeon = "Saron's Mine",
            dungeonEN = "Pit of Saron",
            spells = {
                [1261286] = {
                    spellID = 1261286,
                    name = "Throw Saron Scrap",
                    sourceNPCIDs = {252635},
                    bosses = "Forge-Lord Gavust",
                    sources = {"Forgemaster Garfrost"},
                },
                [1261540] = {
                    spellID = 1261540,
                    name = "Ore Crusher",
                    sourceNPCIDs = {252635},
                    bosses = "Forge-Lord Gavust",
                    sources = {"Forgemaster Garfrost"},
                },
                [1261799] = {
                    spellID = 1261799,
                    name = "Saron Scrap Sludge",
                    sourceNPCIDs = {252635},
                    bosses = "Forge-Lord Gavust",
                    sources = {"Forgemaster Garfrost"},
                },
                [1262596] = {
                    spellID = 1262596,
                    name = "Plague-Lord's Mark",
                    sourceNPCIDs = {252648},
                    bosses = "Plague-Lord Tyranus",
                    sources = {"Scourgelord Tyrannus"},
                },
                [1262772] = {
                    spellID = 1262772,
                    name = "Frost Shock",
                    sourceNPCIDs = {252653},
                    bosses = "Plague-Lord Tyranus",
                    sources = {"Rimefang"},
                },
                [1263716] = {
                    spellID = 1263716,
                    name = "Frost Bite",
                    sourceNPCIDs = {252653},
                    bosses = "Plague-Lord Tyranus",
                    sources = {"Rimefang"},
                },
                [1264246] = {
                    spellID = 1264246,
                    name = "Shadow Shift",
                    sourceNPCIDs = {252621},
                    bosses = "Ikk and Korik",
                    sources = {"Krick"},
                },
                [1264299] = {
                    spellID = 1264299,
                    name = "Wither",
                    sourceNPCIDs = {252625},
                    bosses = "Ikk and Korik",
                    sources = {"Ick"},
                },
                [1264453] = {
                    spellID = 1264453,
                    name = "Lumbering Gaze",
                    sourceNPCIDs = {252625},
                    bosses = "Ikk and Korik",
                    sources = {"Ick"},
                },
                [1275687] = {
                    spellID = 1275687,
                    name = "Glacier Overload",
                    sourceNPCIDs = {},
                    bosses = "Forge-Lord Gavust",
                    sources = {"Forge"},
                },
                [1276648] = {
                    spellID = 1276648,
                    name = "Bone Infusion",
                    sourceNPCIDs = {252648},
                    bosses = "Plague-Lord Tyranus",
                    sources = {"Scourgelord Tyrannus"},
                },
            },
        },
        ["Measara Cavern"] = {
            dungeon = "Measara Cavern",
            dungeonEN = "Maisara Caverns",
            spells = {
                [1249478] = {
                    spellID = 1249478,
                    name = "Carrion Pounce",
                    sourceNPCIDs = {247572},
                    bosses = "Mrokin and Nekrax",
                    sources = {"Nekraxx"},
                },
                [1251775] = {
                    spellID = 1251775,
                    name = "Ultimate Hunt",
                    sourceNPCIDs = {250443},
                    bosses = "Vodaza",
                    sources = {"Unstable Phantom"},
                },
                [1252675] = {
                    spellID = 1252675,
                    name = "Crush Soul",
                    sourceNPCIDs = {248605},
                    bosses = "Laktul, Soul-Vessel",
                    sources = {"Rak'tul"},
                },
                [1260643] = {
                    spellID = 1260643,
                    name = "Barrage",
                    sourceNPCIDs = {247570},
                    bosses = "Mrokin and Nekrax",
                    sources = {"Muro'jin"},
                },
            },
        },
        ["Skyveil Peak"] = {
            dungeon = "Skyveil Peak",
            dungeonEN = "Skyreach",
            spells = {
                [153757] = {
                    spellID = 153757,
                    name = "Scatter Blade",
                    sourceNPCIDs = {75964},
                    bosses = "Lanjit",
                    sources = {"Ranjit"},
                },
                [153954] = {
                    spellID = 153954,
                    name = "Hurl Down",
                    sourceNPCIDs = {76266},
                    bosses = "High Sage Virix",
                    sources = {"High Sage Viryx"},
                },
                [154150] = {
                    spellID = 154150,
                    name = "Ray",
                    sourceNPCIDs = {76142},
                    bosses = "High Sage Virix",
                    sources = {"Skyreach Sun Construct Prototype"},
                },
                [1252733] = {
                    spellID = 1252733,
                    name = "Gale Rush",
                    sourceNPCIDs = {75964},
                    bosses = "Lanjit",
                    sources = {"Ranjit"},
                },
                [1253511] = {
                    spellID = 1253511,
                    name = "Ignite Pursuit",
                    sourceNPCIDs = {76227},
                    bosses = "Ruklan",
                    sources = {"Sunwings"},
                },
                [1253520] = {
                    spellID = 1253520,
                    name = "Burning Claw",
                    sourceNPCIDs = {76143},
                    bosses = "Ruklan",
                    sources = {"Rukhran"},
                },
                [1253541] = {
                    spellID = 1253541,
                    name = "Searing Ray",
                    sourceNPCIDs = {76266},
                    bosses = "High Sage Virix",
                    sources = {"High Sage Viryx"},
                },
                [1253543] = {
                    spellID = 1253543,
                    name = "Searing Ray",
                    sourceNPCIDs = {76285},
                    bosses = "High Sage Virix",
                    sources = {"Arakkoa Magnifying Glass"},
                },
            },
        },
        ["Windrunner's Spire"] = {
            dungeon = "Windrunner's Spire",
            dungeonEN = "Windrunner Spire",
            spells = {
                [467620] = {
                    spellID = 467620,
                    name = "Enrage",
                    sourceNPCIDs = {231631},
                    bosses = "Commander Koruko",
                    sources = {"Commander Kroluk"},
                },
                [470966] = {
                    spellID = 470966,
                    name = "Bladestorm",
                    sourceNPCIDs = {},
                    bosses = "Commander Koruko",
                    sources = {"Environment"},
                },
                [472662] = {
                    spellID = 472662,
                    name = "Stormstrike",
                    sourceNPCIDs = {231636},
                    bosses = "Sleepless Heart",
                    sources = {"Restless Heart"},
                },
                [472793] = {
                    spellID = 472793,
                    name = "Powerful Drag",
                    sourceNPCIDs = {231629},
                    bosses = "Forsaken Duo",
                    sources = {"Latch"},
                },
                [474129] = {
                    spellID = 474129,
                    name = "Splatter Spit",
                    sourceNPCIDs = {231629},
                    bosses = "Forsaken Duo",
                    sources = {"Latch"},
                },
                [1253979] = {
                    spellID = 1253979,
                    name = "Forceful Shot",
                    sourceNPCIDs = {231636},
                    bosses = "Sleepless Heart",
                    sources = {"Restless Heart"},
                },
                [1282911] = {
                    spellID = 1282911,
                    name = "Arrow Storm",
                    sourceNPCIDs = {231636},
                    bosses = "Sleepless Heart",
                    sources = {"Restless Heart"},
                },
                [1283247] = {
                    spellID = 1283247,
                    name = "Merciless Leap",
                    sourceNPCIDs = {231631},
                    bosses = "Commander Koruko",
                    sources = {"Commander Kroluk"},
                },
            },
        },
        ["Arcanist Platform"] = {
            dungeon = "Arcanist Platform",
            dungeonEN = "Magisters' Terrace",
            spells = {
                [1225792] = {
                    spellID = 1225792,
                    name = "Rune Brand",
                    sourceNPCIDs = {231863},
                    bosses = "Ceranael Sunlash",
                    sources = {"Seranel Sunlash"},
                },
                [1253709] = {
                    spellID = 1253709,
                    name = "Neural Link",
                    sourceNPCIDs = {231864, 239636},
                    bosses = "Gimelrus",
                    sources = {"Gemellus"},
                },
                [1269631] = {
                    spellID = 1269631,
                    name = "Entropy Orb",
                    sourceNPCIDs = {231865},
                    bosses = "Dijantreous",
                    sources = {"Degentrius"},
                },
            },
        },
    },
}
