---@diagnostic disable: undefined-global
-- Auto-generated, do not edit manually
-- Generated: 2026-03-18 08:19:23
-- 68 labels

-- InfinityBossVoice voice pack label list
EXBV_LABELS = {
        "Prepare AOE",
        "Prepare Beam",
        "Prepare Interrupt",
        "Prepare Pull",
        "Prepare Block Line",
        "Prepare Soak",
        "Prepare Clear Stack",
        "Prepare Target",
        "Prepare Arrow",
        "Prepare Enter Circle",
        "Prepare Link",
        "Prepare Ball",
        "Prepare Hook",
        "Prepare Stack",
        "Prepare Dispel",
        "Hit Clone",
        "Tank Buster",
        "Fix Camera",
        "Clear Water",
        "Find Beacon",
        "Step Trap",
        "None",
        "Watch Knockback",
        "Watch Frontal",
        "Block Ball",
        "Clear Ball",
        "Watch Dodge",
        "Target Frontal",
        "Target Drop Water",
        "Target Clear Line",
        "Dodge Frontal",
        "Switch Add",
        "Phase Change",
        "Away Boss",
        "Spread Close",
        "Kite Add",
        "Boss Enrage",
        "Boss Vuln",
        "You White",
        "You Black",
        "Prepare AOE Break",
        "Prepare Absorb Ball",
        "Drop Water",
        "Intercept Add",
        "Beam On You",
        "Watch Shockwave",
        "Watch Launch",
        "Empower HPal",
        "Empower Ret",
        "Empower Prot",
        "Spread Now",
        "Interrupt Now",
        "Rescue Now",
        "Break Shield",
        "Enter Bubble",
        "Break Link",
        "Vuln Burst",
        "Use Defensive",
        "Watch Healing",
        "Special Mechanic",
        "Switch Boss",
        "Away Add",
        "Stack Share",
        "Countdown 5",
        "Countdown 4",
        "Countdown 3",
        "Countdown 2",
        "Countdown 1",
}
InfinityBossVoiceLabels = EXBV_LABELS -- backwards compatibility alias
